//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.08 at 11:47:17 AM PST 
//


package com.gc.ims.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MuseumInfo" type="{http://www.tcss559.com/xml/museum}MuseumInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "museumInfo"
})
@XmlRootElement(name = "MuseumInfoResponse")
public class MuseumInfoResponse {

    @XmlElement(name = "MuseumInfo", required = true)
    protected MuseumInfo museumInfo;

    /**
     * Gets the value of the museumInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MuseumInfo }
     *     
     */
    public MuseumInfo getMuseumInfo() {
        return museumInfo;
    }

    /**
     * Sets the value of the museumInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MuseumInfo }
     *     
     */
    public void setMuseumInfo(MuseumInfo value) {
        this.museumInfo = value;
    }

}
