//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.08 at 11:47:17 AM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tcss559.com/xml/museum", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gc.ims.ws;
